version: '2'
services:
  #misc
  rabbitmq:
    ports:
    - 5671
    - 5672
    - 15672
    image: rabbitmq:${RABBITMQ_VERSION}

  http:
    environment:
      SERVICE_CHECK_HTTP: ':80/'
    image: nginx

  fireandforget:
    build: ./fireandforget
    environment:
      SERVICE_CHECK_EXIT: 'true'

  mockservice:
    ports:
    - 8080
    - 8090
    command: ["/opt/mockserver/run_mockserver.sh", "-logLevel", "INFO", "-proxyPort", "8090", "-serverPort","8080"]
    image: jamesdbloom/mockserver:${MOCKSERVER_VERSION}